import { Post } from 'src/posts/entities/post.entity';

export default [
    {
        id: '6610e8a2-4833-4208-8b5d-864f8bbe8202',
        title: 'Post 1',
        contentMarkdown: 'Content for post 1',
        topicId: 1,
        userId: '1',
        readyState: 1,
        imageUrl: 'https://example.com/image1.jpg',
        contentHTML: '<p>Content for post 1</p>',
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '8413ceb2-4934-4927-90ae-549d44930418',
        title: 'Post 2',
        contentMarkdown: 'Content for post 2',
        readyState: 1,
        userId: '2',
        imageUrl: 'https://example.com/image2.jpg',
        contentHTML: '<p>Content for post 2</p>',
        topicId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '5878ff49-933d-4c7c-9f68-d93afa8f59bb',
        title: 'Post 3',
        contentMarkdown: 'Content for post 3',
        topicId: 2,
        readyState: 1,
        userId: '3',
        imageUrl: 'https://example.com/image3.jpg',
        contentHTML: '<p>Content for post 3</p>',
        createdAt: new Date(),
        updatedAt: new Date(),
    },
] as Post[];
